// All page copy. Arrays are positional: they line up with the icons, images and
// numbers defined in components/landing.tsx and components/setups-gallery.tsx.

const en = {
  dir: "ltr",
  switchLabel: "العربية",
  switchHref: "/ar",
  brand: ["Arraya", "Ballroom"],
  enquire: "Enquire",
  nav: ["Events", "Setups", "Capacity", "Facilities", "Location"],
  hero: {
    eyebrow: "Sharq · Kuwait City",
    title: "Where Kuwait gathers for its grandest occasions",
    body: "A 1,482 m² ballroom that opens as one breathtaking space or divides into six salons - for weddings, conferences and celebrations of up to 2,000 guests.",
    primary: "Explore setups",
    secondary: "Plan your event",
    alt: "Arraya Ballroom dressed for a wedding with porcelain lanterns",
  },
  stats: [
    ["1,482 m²", "Grand ballroom"],
    ["6", "Divisible salons"],
    ["2,000", "Guests, theatre style"],
    ["8 m", "Maximum ceiling"],
  ],
  intro: {
    eyebrow: "The Ballroom",
    title: "One ballroom. Six salons. Endless possibilities.",
    p1: "Arraya Ballroom sits in the heart of the Sharq business district, adjacent to the Arraya shopping complex and the Courtyard by Marriott - 15 minutes from Kuwait International Airport. Guests arrive by valet straight into a 387 m² foyer, while planners enjoy street-level loading, rigging-ready ceilings and an event, AV and engineering team on site.",
    p2: "From an intimate 100-guest dinner in Salon 1 to a 2,000-seat summit across the Grand Ballroom, every event is tailored, staged and served with traditional Arabic hospitality.",
    alts: ["Wedding cake under a gilded arch", "Formal conference stage with flags"],
  },
  events: {
    eyebrow: "Events",
    title: "Made for every occasion",
    items: [
      ["Weddings", "Ladies' weddings and receptions for up to 800, with a private bridal suite and traditional Arabic hospitality."],
      ["Conferences", "Summits, AGMs and government delegations with in-built screens, projectors and an on-site AV team."],
      ["Graduations & Galas", "Runways, light arches and staging from 20 to 60 cm for ceremonies, award nights and launches."],
      ["Training & Exhibitions", "Classroom layouts for 1,500, a 2.5 t/m² floor load and street-level loading for exhibition builds."],
    ],
  },
  setups: {
    eyebrow: "Setups",
    title: "See the ballroom transformed",
    tabs: {
      weddings: ["Weddings", "Ladies' weddings and receptions for up to 800 guests - kosha stages, lounge seating, floral ceilings and a full-length runway."],
      conference: ["Conference", "Theatre-style seating for up to 2,000 delegates with in-built 6 × 4 m screens, staging and an on-site AV team."],
      classroom: ["Classroom", "Classroom layouts for up to 1,500 - training, exams and workshops with power and data every 3.5 m."],
      graduation: ["Graduation & Gala", "Runways, illuminated arches and theatrical lighting for ceremonies, award nights and launches."],
      space: ["The Space", "A blank canvas: 57 × 26 m, 8 m maximum ceiling, rigging-ready and loaded straight from street level."],
    } as Record<string, [string, string]>,
    alts: {
      "20": "Blue-and-white porcelain wedding hall with lantern ceiling",
      "17": "Porcelain-painted wedding cake beneath a gilded archway",
      "21": "Runway between lounge seating under porcelain lanterns",
      "18": "Ivory sofa lounge against a hand-painted chinoiserie wall",
      "22": "Porcelain lantern installation over guest lounges",
      "19": "Close-up of ivory lounge seating with porcelain accents",
      "10": "Garden wedding with suspended white floral ceiling",
      "03": "Illuminated kosha stage framed by white florals",
      "05": "Wrought-iron floral dome at the end of the runway",
      "02": "Arched bridal entrance with chandelier and cake",
      "04": "Green velvet lounge seating with floral centrepieces",
      "16": "Silver buffet with candelabra and floral canopy",
      "25": "Theatre-style conference with LED screens and centre aisle",
      "26": "Formal conference with podium, flags and gold chairs",
      "27": "Delegation stage set with national flags and chandeliers",
      "23": "Classroom setup facing a large LED wall",
      "24": "Rows of classroom tables beneath crystal chandeliers",
      "28": "Graduation runway with illuminated arches and LED screens",
      "01": "The empty ballroom with lighting truss during build",
      floorplan: "Floor plan showing the six salons and foyers",
    } as Record<string, string>,
    prev: "Previous photo",
    next: "Next photo",
    close: "Close",
  },
  capacity: {
    eyebrow: "Capacity",
    title: "Floor plan & capacities",
    body: "Movable partitions divide the Grand Ballroom into six salons, combinable in any adjoining arrangement. Ceiling height is 5 m throughout, rising to 8 m at its highest point.",
    planAlt: "Floor plan of Arraya Ballroom showing six salons",
    headers: ["Room", "Size (m)", "Area m²", "Theatre", "Classroom", "Reception", "Banquet", "U-Shape"],
    rooms: [
      "Grand Ballroom",
      "Salon 2 & 3",
      "Salon 1, 2 & 5",
      "Salon 3, 4 & 6",
      "Salon 2 · Bubyan",
      "Salon 3 · Warba",
      "Salon 1 & 5",
      "Salon 4 & 6",
      "Salon 5 · Um Al Maradim",
      "Salon 6 · Failaka",
      "Salon 1 · Farwa",
      "Salon 4 · Misjal",
    ],
  },
  facilities: {
    eyebrow: "Facilities",
    title: "Everything handled, in house",
    items: [
      ["Event team on site", "Dedicated event management, engineering and technical support."],
      ["In-built AV", "Two 6 × 4 m screens, two projectors, LCD, plasma and a resident AV team."],
      ["Power & data", "Three-phase power; electricity, phone and internet every 3.5 m."],
      ["Flexible staging", "Stage heights 20-60 cm, dance floor, banquet to cocktail tables."],
      ["Arabic hospitality", "Arabic coffee, bokhour and rose water served by our team."],
      ["Valet & parking", "Valet from the driveway into a 387 m² foyer; 1,000+ parking bays."],
      ["Direct loading", "Street-level loading access and a 2.5 t/m² floor load."],
      ["Private suites", "Bridal suite plus two private suites and meeting rooms."],
      ["Rigging-ready", "5-8 m ceilings ready for truss, lighting and set builds."],
    ],
  },
  contact: {
    eyebrow: "Plan your event",
    title: "Let's create something unforgettable",
    body: "Share your date, guest count and vision - our event team will come back with layouts, menus and a tailored proposal.",
    primary: "Send an enquiry",
    directions: "Get directions",
    venue: "Arraya Ballroom",
    address: ["Arraya Shopping Complex, Sharq", "Kuwait City, Kuwait"],
    airportTitle: "From the airport",
    airport: "15 min via Highway 50 to Liberation Tower, then Al Shuhada Street. Entrance on your right at Arraya Mall.",
    call: "Call us",
    email: "Email",
    hotel: "Overnight guests are steps away at the adjoining Courtyard by Marriott - airport meet & assist, concierge, pool, health club and designer shopping next door.",
  },
  footer: { rights: "Arraya Ballroom Kuwait", enquiries: "Enquiries" },
  emailSubject: "Arraya Ballroom enquiry",
}

export type Content = typeof en

const ar: Content = {
  dir: "rtl",
  switchLabel: "English",
  switchHref: "/",
  brand: ["قاعة", "الراية"],
  enquire: "استفسر الآن",
  nav: ["المناسبات", "التجهيزات", "السعة", "المرافق", "الموقع"],
  hero: {
    eyebrow: "شرق · مدينة الكويت",
    title: "حيث تجتمع الكويت لأرقى مناسباتها",
    body: "قاعة بمساحة 1,482 م² تُفتح كمساحة واحدة مبهرة أو تُقسَّم إلى ستة صالونات - لحفلات الزفاف والمؤتمرات والاحتفالات حتى 2,000 ضيف.",
    primary: "استكشف التجهيزات",
    secondary: "خطط لمناسبتك",
    alt: "قاعة الراية مجهزة لحفل زفاف بفوانيس من الخزف",
  },
  stats: [
    ["1,482 م²", "القاعة الكبرى"],
    ["6", "صالونات قابلة للتقسيم"],
    ["2,000", "ضيف بنظام المسرح"],
    ["8 م", "أقصى ارتفاع للسقف"],
  ],
  intro: {
    eyebrow: "القاعة",
    title: "قاعة واحدة. ستة صالونات. إمكانيات لا حدود لها.",
    p1: "تقع قاعة الراية في قلب منطقة شرق، مركز المال والأعمال، بجوار مجمع الراية للتسوق وفندق كورت يارد ماريوت - على بعد 15 دقيقة من مطار الكويت الدولي. يصل الضيوف عبر خدمة صف السيارات مباشرة إلى بهو استقبال بمساحة 387 م²، بينما يستفيد المنظمون من التحميل المباشر من مستوى الشارع وأسقف جاهزة للتعليق وفريق متخصص للفعاليات والصوت والإضاءة والهندسة في الموقع.",
    p2: "من عشاء خاص لـ 100 ضيف في الصالون 1 إلى قمة تضم 2,000 مقعد في القاعة الكبرى، تُصمَّم كل مناسبة وتُجهَّز وتُقدَّم بكرم الضيافة العربية الأصيلة.",
    alts: ["كعكة زفاف تحت قوس مذهّب", "منصة مؤتمر رسمي مع الأعلام"],
  },
  events: {
    eyebrow: "المناسبات",
    title: "مصممة لكل مناسبة",
    items: [
      ["حفلات الزفاف", "أعراس نسائية وحفلات استقبال حتى 800 ضيفة، مع جناح خاص للعروس وخدمات الضيافة العربية التقليدية."],
      ["المؤتمرات", "قمم وجمعيات عمومية ووفود حكومية مع شاشات وأجهزة عرض مدمجة وفريق صوت وإضاءة في الموقع."],
      ["التخرج والحفلات الكبرى", "ممرات عرض وأقواس مضيئة ومسارح بارتفاع 20 إلى 60 سم للاحتفالات وحفلات التكريم والإطلاق."],
      ["التدريب والمعارض", "ترتيب الصف الدراسي حتى 1,500 شخص، وحمولة أرضية 2.5 طن/م²، وتحميل مباشر من الشارع للمعارض."],
    ],
  },
  setups: {
    eyebrow: "التجهيزات",
    title: "شاهد القاعة بحلّتها المختلفة",
    tabs: {
      weddings: ["حفلات الزفاف", "أعراس نسائية وحفلات استقبال حتى 800 ضيفة - كوشة ومجالس وأسقف من الزهور وممر عرض كامل."],
      conference: ["المؤتمرات", "جلوس بنظام المسرح حتى 2,000 مشارك مع شاشات مدمجة 6 × 4 م ومسرح وفريق صوت وإضاءة في الموقع."],
      classroom: ["الصف الدراسي", "ترتيب الصف الدراسي حتى 1,500 شخص - للتدريب والاختبارات وورش العمل مع توصيلات كهرباء وإنترنت كل 3.5 م."],
      graduation: ["التخرج والحفلات", "ممرات عرض وأقواس مضيئة وإضاءة مسرحية للاحتفالات وحفلات التكريم والإطلاق."],
      space: ["المساحة", "مساحة مفتوحة للإبداع: 57 × 26 م، بارتفاع سقف يصل إلى 8 م، جاهزة للتعليق مع تحميل مباشر من الشارع."],
    },
    alts: {
      "20": "قاعة زفاف بطابع الخزف الأزرق والأبيض وسقف من الفوانيس",
      "17": "كعكة زفاف مزخرفة بالخزف تحت قوس مذهّب",
      "21": "ممر العروس بين المجالس تحت فوانيس الخزف",
      "18": "مجلس بأرائك عاجية أمام جدارية مرسومة يدوياً",
      "22": "تنسيق فوانيس الخزف فوق مجالس الضيوف",
      "19": "لقطة قريبة لمجلس عاجي بلمسات خزفية",
      "10": "حفل زفاف بطابع الحديقة وسقف من الزهور البيضاء",
      "03": "كوشة مضيئة محاطة بالزهور البيضاء",
      "05": "قبة من الحديد المشغول والزهور في نهاية الممر",
      "02": "مدخل العروس المقوّس مع ثريا وكعكة الزفاف",
      "04": "مجالس مخملية خضراء مع تنسيقات زهور",
      "16": "بوفيه فضي مع شمعدانات ومظلة من الزهور",
      "25": "مؤتمر بنظام المسرح مع شاشات LED وممر أوسط",
      "26": "مؤتمر رسمي مع منصة وأعلام وكراسٍ ذهبية",
      "27": "منصة وفود مع الأعلام الوطنية والثريات",
      "23": "ترتيب صف دراسي أمام شاشة LED كبيرة",
      "24": "صفوف طاولات دراسية تحت ثريات كريستالية",
      "28": "ممر تخرج بأقواس مضيئة وشاشات LED",
      "01": "القاعة فارغة مع هياكل الإضاءة أثناء التجهيز",
      floorplan: "مخطط القاعة يوضح الصالونات الستة وبهو الاستقبال",
    },
    prev: "الصورة السابقة",
    next: "الصورة التالية",
    close: "إغلاق",
  },
  capacity: {
    eyebrow: "السعة",
    title: "مخطط القاعة والسعة",
    body: "تُقسَّم القاعة الكبرى بفواصل متحركة إلى ستة صالونات يمكن دمجها بأي ترتيب متجاور. ارتفاع السقف 5 م في جميع الأقسام ويصل إلى 8 م في أعلى نقطة.",
    planAlt: "مخطط قاعة الراية يوضح الصالونات الستة",
    headers: ["القاعة", "الأبعاد (م)", "المساحة م²", "مسرح", "صف دراسي", "استقبال", "مأدبة", "حرف U"],
    // ponytail: island names left out in Arabic - add once official spellings are confirmed
    rooms: [
      "القاعة الكبرى",
      "الصالون 2 و 3",
      "الصالونات 1 و 2 و 5",
      "الصالونات 3 و 4 و 6",
      "الصالون 2",
      "الصالون 3",
      "الصالون 1 و 5",
      "الصالون 4 و 6",
      "الصالون 5",
      "الصالون 6",
      "الصالون 1",
      "الصالون 4",
    ],
  },
  facilities: {
    eyebrow: "المرافق",
    title: "كل ما تحتاجه، بين أيدينا",
    items: [
      ["فريق فعاليات في الموقع", "فريق متمرس لتنظيم وإدارة الحفلات والمؤتمرات مع دعم هندسي وفني."],
      ["صوت وعرض مدمج", "شاشتان 6 × 4 م وجهازا عرض وشاشات LCD وبلازما وفريق صوت وإضاءة مقيم."],
      ["كهرباء وإنترنت", "كهرباء ثلاثية الطور، وتوصيلات كهرباء وهاتف وإنترنت كل 3.5 م."],
      ["مسارح مرنة", "ارتفاعات مسرح من 20 إلى 60 سم، وساحة رقص، وطاولات من المآدب إلى الكوكتيل."],
      ["ضيافة عربية", "القهوة العربية والبخور وماء الورد يقدمها فريقنا."],
      ["صف السيارات والمواقف", "خدمة صف السيارات حتى بهو بمساحة 387 م²، ومواقف لأكثر من 1,000 سيارة."],
      ["تحميل مباشر", "تحميل وتفريغ مباشر من مستوى الشارع وحمولة أرضية 2.5 طن/م²."],
      ["أجنحة خاصة", "جناح للعروس وجناحان خاصان وقاعتا اجتماعات."],
      ["جاهزة للتعليق", "أسقف من 5 إلى 8 م جاهزة لهياكل الإضاءة والديكور."],
    ],
  },
  contact: {
    eyebrow: "خطط لمناسبتك",
    title: "لنصنع معاً مناسبة لا تُنسى",
    body: "شاركنا التاريخ وعدد الضيوف ورؤيتك - وسيعود إليك فريقنا بالمخططات وقوائم الطعام وعرض مصمم خصيصاً لك.",
    primary: "أرسل استفسارك",
    directions: "الاتجاهات",
    venue: "قاعة الراية",
    address: ["مجمع الراية للتسوق، شرق", "مدينة الكويت، الكويت"],
    airportTitle: "من المطار",
    airport: "15 دقيقة عبر طريق 50 حتى تقاطع برج التحرير، ثم شارع الشهداء. المدخل على يمينك عند مجمع الراية.",
    call: "اتصل بنا",
    email: "البريد الإلكتروني",
    hotel: "يقيم الضيوف على بعد خطوات في فندق كورت يارد ماريوت المجاور - استقبال في المطار، ومكتب استعلامات، ومسبح، ونادٍ صحي، ومجمع تسوق للماركات العالمية.",
  },
  footer: { rights: "قاعة الراية الكويت", enquiries: "للاستفسار" },
  emailSubject: "استفسار عن قاعة الراية",
}

export const content = { en, ar }
export type Lang = keyof typeof content
